# Builds mdriver-viz = mdriver + viz.c, without editing mm.c or Makefile.
#   make -f Makefile.viz
#   ./mdriver-viz -V -f short1-bal.rep          (VIZ=bar for colored bars)
CC = gcc
CFLAGS = -Wall -O2 -g

OBJS = mdriver.o mm.o memlib.o fsecs.o fcyc.o clock.o ftimer.o viz.o

mdriver-viz: $(OBJS)
	$(CC) $(CFLAGS) -Wl,--wrap=mm_malloc,--wrap=mm_free,--wrap=mm_realloc -o $@ $(OBJS)

clean:
	rm -f *.o mdriver-viz
